site_name: noc.level66.network
site_url: https://noc.level66.network/
site_author: "level66.network UG (haftungsbeschränkt)"
site_description: "This website describes the technical side of AS56381 operated by level66.network UG (haftungsbeschränkt)."
copyright: "Copyright by level66.network UG (haftungsbeschränkt)"

theme: readthedocs

nav:
  - General:
    - Home: index.md
    - Imprint: https://level66.network/impressum/
  - Services:
    - DNS: ./services/dns.md
    - NTP: ./services/ntp.md
    - NAT64: ./services/nat64.md
    - Mirror: ./services/mirror.md
  - Tools:
    - Speedtest: ./tools/speedtest.md
    - Looking Glass: https://lg.noc.level66.network/
    - Smokeping: https://ping.noc.level66.network/
    - Status Page: https://status.level66.network/
  - External Statistics:
    - bgp.tools: https://bgp.tools/as/56381
    - bgp.he.net: https://bgp.he.net/AS56381
