site_name: noc.level66.network
site_url: https://noc.level66.network/
site_author: "level66.network UG (haftungsbeschränkt)"
site_description: "This website describes the technical side of AS56381 operated by level66.network UG (haftungsbeschränkt)."
copyright: "Copyright by level66.network UG (haftungsbeschränkt)"

theme:
  name: lux
  navigation_depth: 4

nav:
  - Home: index.md
  - BGP Looking Glass: https://lg.noc.level66.network/
  - BGP Communities: bgp-communities.md
  - Imprint: https://level66.network/impressum/
