site_name: level66.services
site_url: https://level66.services/
site_author: "level66.network UG (haftungsbeschränkt)"
site_description: "This website describes the services provided by level66.network."
copyright: "Copyright by level66.network UG (haftungsbeschränkt)"

theme: readthedocs

nav:
  - General:
    - Home: index.md
    - Status Page: https://status.level66.services/
    - Ticket System: https://support.level66.network/
    - Privacy: https://level66.network/datenschutz/
    - Imprint: https://level66.network/impressum/

  - Services:
    - DNS Server: ./services/dns.md
    - NTP Server: ./services/ntp.md
    - NAT64 Gateway: ./services/nat64.md
    - RPKI Validator / RTR Server: ./services/rpki.md
    - Software Mirror: ./services/mirror.md
    - Speedtest Server: ./services/speedtest.md

  - Network Backbone:
    - AS56381: ./as56381/index.md
    - Looking Glass: https://lg.level66.services/
    - bgp.tools: https://bgp.tools/as/56381
    - bgp.he.net: https://bgp.he.net/AS56381
